### ISSUE TITLE
Is there any way to set shippingType, requiredShippingContactFields & requiredBillingContactFields in ApplePayMerchantConfiguration?

### ISSUE THREAD

**Issue by piyush-bryj** [verifoneone/verifone-ecom-ios-sdk#2]
Hello, 

I want to add shippingType, requiredShippingContactFields & requiredBillingContactFields filed into the PKPaymentRequest. I didn't find any way to add those inside the ApplePayMerchantConfiguration. 

Let me know if there is any way to add those. 

Thanks

<img width="585" alt="Screenshot 2023-06-12 at 3 54 34 PM" src="https://github.com/verifoneone/verifone-ecom-ios-sdk/assets/108368167/71caa82d-cf8c-43da-8d44-67762cd29c4c">

**Comment by craigchristenson** [comment]
This was added in the 1.3.0 release.
https://github.com/verifoneone/verifone-ecom-ios-sdk/commit/5ab3af75c26c9f3366d8f24d8261fcfe4394a291
