### ISSUE TITLE
Code 400 - Failed to decrypt apple pay wallet payload / invalid token

### ISSUE THREAD

**Issue by piyush-bryj** [verifoneone/verifone-ecom-ios-sdk#3]
Hello, I'm trying to call eCom Wallet Transaction API, But getting the following response code. 

let me know if you have idea about the same? Thanks 

![Screenshot 2023-06-19 at 1 13 23 PM](https://github.com/verifoneone/verifone-ecom-ios-sdk/assets/108368167/6ed837c5-76a4-4a9b-b29c-1eb52ce0c1da)

**Comment by craigchristenson** [comment]
This indicates that Verifone was not able to decrypt the wallet payload that you sent using the Apple Pay wallet contract that you onboarded with them. You will need to make sure that your wallet contract was onboarded properly with the merchant id that you are bundling with your app. Please reach out to Verifone support for assistance with this.
